
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Timer;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MSI-OFFICE
 */
public class TrangChuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public TrangChuJFrame() {
        initComponents();
        showTime();
    }
    
    public void showTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            Date currentTimeDate = new Date();
            jMenuTime.setText(currentTimeDate.toString());
            }
        });
        timer.start();
    }
    
    
    public TrangChuJFrame(String username) {
        initComponents();
        showTime();
        PreparedStatement pst = null;
        PreparedStatement pst1 = null;
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
            String sql = "SELECT * FROM USER WHERE USERNAME = ? AND PASSWORD = ?";
            String sql1 = "SELECT * FROM KHACHHANG WHERE USERNAME = ? AND PASSWORD = ?";
            pst = conn.prepareStatement(sql);
            pst1 = conn.prepareStatement(sql1);
            pst.setString(1, username);
            pst1.setString(1, username);
            pst.setString(2, username);
            pst1.setString(2, username);
            ResultSet resultSet = pst.executeQuery();
            ResultSet resultSet1 = pst1.executeQuery();
            if (resultSet.next()) {
                jButtonVatTu.setVisible(true);
                jButtonKhachHang.setVisible(true);
                jButtonHoaDon.setVisible(true);
                jButtonThongKe.setVisible(true);
                jLabelVaiTro.setText("Quản trị viên");
                jLabelTenDangNhap.setText(username);
                } 
            else if (resultSet1.next()) {
                jButtonVatTu.setVisible(false);
                jButtonThongKe.setVisible(false);
                jLabelVaiTro.setText("Thành viên");
                jLabelTenDangNhap.setText(username);
                
            }
        } catch (SQLException ex) {
                ex.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonVatTu = new javax.swing.JButton();
        jButtonKhachHang = new javax.swing.JButton();
        jButtonHoaDon = new javax.swing.JButton();
        jLabelVaiTro = new javax.swing.JLabel();
        jButtonThongKe = new javax.swing.JButton();
        jLabelTenDangNhap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTime = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDangKy = new javax.swing.JMenuItem();
        jMenuItemDangXuat = new javax.swing.JMenuItem();
        jMenuItemThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(228, 252, 255));

        jPanel2.setBackground(new java.awt.Color(228, 255, 254));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jButtonVatTu.setBackground(new java.awt.Color(128, 153, 224));
        jButtonVatTu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVatTu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVatTu.setText("Vật Tư");
        jButtonVatTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVatTuActionPerformed(evt);
            }
        });

        jButtonKhachHang.setBackground(new java.awt.Color(128, 153, 224));
        jButtonKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKhachHang.setText("Khách Hàng");
        jButtonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhachHangActionPerformed(evt);
            }
        });

        jButtonHoaDon.setBackground(new java.awt.Color(128, 153, 224));
        jButtonHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHoaDon.setText("Hóa Đơn");
        jButtonHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHoaDonActionPerformed(evt);
            }
        });

        jLabelVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelVaiTro.setForeground(new java.awt.Color(255, 255, 255));

        jButtonThongKe.setBackground(new java.awt.Color(128, 153, 224));
        jButtonThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThongKe.setText("Thống Kê");
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonVatTu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jButtonHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButtonThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonVatTu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jLabelTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Xin chào, ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 610, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 255, 255));

        jMenuTime.setText("Ngày giờ");
        jMenuTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTimeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuTime);

        jMenu2.setText("Tiện ích");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItemDangKy.setText("Đăng ký");
        jMenuItemDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangKyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDangKy);

        jMenuItemDangXuat.setText("Đăng Xuất");
        jMenuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDangXuat);

        jMenuItemThoat.setText("Thoát Ứng Dụng");
        jMenuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThoatActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemThoat);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangXuatActionPerformed
        // TODO add your handling code here:
        dispose();
        DangNhapJFrame vattu = new DangNhapJFrame();
        vattu.setTitle("Đăng nhập ứng dụng");
        vattu.setVisible(true);
    }//GEN-LAST:event_jMenuItemDangXuatActionPerformed

    private void jMenuItemDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangKyActionPerformed
        // TODO add your handling code here:
        DangKyJFrame frmDangKy = new DangKyJFrame();
        frmDangKy.setVisible(true);
    }//GEN-LAST:event_jMenuItemDangKyActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemThoatActionPerformed

    private void jButtonVatTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVatTuActionPerformed
        // TODO add your handling code here:
        VatTuJFrame vattu = new VatTuJFrame();
        vattu.setTitle("Quản Lý Vật Tư");
        vattu.setVisible(true);
    }//GEN-LAST:event_jButtonVatTuActionPerformed

    private void jButtonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhachHangActionPerformed
        // TODO add your handling code here:
        String vaitro = jLabelVaiTro.getText();
        String tendangnhap = jLabelTenDangNhap.getText();
        if(vaitro.equals("Quản trị viên")) {
            KhachHangJFrame khachhang = new KhachHangJFrame(vaitro);
            khachhang.setTitle("Quản Lý Khách Hàng");
            khachhang.setVisible(true);
        } else {
            KhachHangJFrame khachhang = new KhachHangJFrame();
            khachhang.setTitle("Quản Lý Thông Tin");
            khachhang.setVisible(true);
        }
    }//GEN-LAST:event_jButtonKhachHangActionPerformed

    private void jButtonHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHoaDonActionPerformed
        // TODO add your handling code here:
        String vaitro = jLabelVaiTro.getText();
        String tendangnhap = jLabelTenDangNhap.getText();
        if(vaitro.equals("Quản trị viên")) {
            HoaDonJFrame khachhang = new HoaDonJFrame(vaitro);
            khachhang.setTitle("Quản Lý Hóa Đơn");
            khachhang.setVisible(true);
        } else {
            HoaDonJFrame khachhang = new HoaDonJFrame();
            khachhang.setTitle("Quản Lý Hóa Đơn Mua Hàng");
            khachhang.setVisible(true);
        }
    }//GEN-LAST:event_jButtonHoaDonActionPerformed

    private void jMenuTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTimeActionPerformed

    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThongKeActionPerformed
        // TODO add your handling code here:
        ThongKeJFrame thongke = new ThongKeJFrame();
        thongke.setTitle("Quản Lý Thống Kê");
        thongke.setVisible(true);
    }//GEN-LAST:event_jButtonThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHoaDon;
    private javax.swing.JButton jButtonKhachHang;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonVatTu;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelTenDangNhap;
    public static javax.swing.JLabel jLabelVaiTro;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDangKy;
    private javax.swing.JMenuItem jMenuItemDangXuat;
    private javax.swing.JMenuItem jMenuItemThoat;
    private javax.swing.JMenu jMenuTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
