
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MSI-OFFICE
 */
public class VatTuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VatTuJFrame
     */ 
    public VatTuJFrame() {
        initComponents();
        ganDuLieu();   
    }
   
    boolean blnThem = false;
    boolean blnSua = false;
    
    public void ganDuLieu() {
        PreparedStatement pst = null;
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
            String sql = "SELECT * FROM VATTU";
            pst = conn.prepareStatement(sql);
            ResultSet resultSet = pst.executeQuery();
            jTableVatTu.setModel(DbUtils.resultSetToTableModel(resultSet));
            
            if(jTableVatTu.getRowCount() > 0) {
                DefaultTableModel tblModel = (DefaultTableModel)jTableVatTu.getModel();
                
                String mavt = tblModel.getValueAt(0,0).toString();
                String tenvt = tblModel.getValueAt(0,1).toString();
                String dvt = tblModel.getValueAt(0,2).toString();
                String giamua = tblModel.getValueAt(0,3).toString();
                String slton = tblModel.getValueAt(0,4).toString();
                
                jTextFieldMa.setText(mavt);
                jTextFieldMa.setEditable(false);
                jTextFieldTen.setText(tenvt);
                jTextFieldTen.setEditable(false);
                jTextFieldDVT.setText(dvt);
                jTextFieldDVT.setEditable(false);
                jTextFieldGiaMua.setText(giamua);
                jTextFieldGiaMua.setEditable(false);
                jTextFieldSoLuongTon.setText(slton);
                jTextFieldSoLuongTon.setEditable(false);
            } else {
                jButtonSua.setEnabled(false);
                jButtonXoa.setEnabled(false);
                jTextFieldMa.setText("");
                jTextFieldTen.setText("");
                jTextFieldDVT.setText("");
                jTextFieldGiaMua.setText("");
                jTextFieldSoLuongTon.setText("");
                
            }
            jButtonLuu.setEnabled(false);
            jButtonKhongLuu.setEnabled(false);
            jButtonXoa.setEnabled(false);
                
        } catch (SQLException ex) {
            String msg = "MyModel(): Error Connecting to Database:\n" + ex.getMessage();
            System.out.println(msg);
        } 
    }


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMa = new javax.swing.JTextField();
        jTextFieldTen = new javax.swing.JTextField();
        jTextFieldDVT = new javax.swing.JTextField();
        jTextFieldGiaMua = new javax.swing.JTextField();
        jTextFieldSoLuongTon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVatTu = new javax.swing.JTable();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonDongForm = new javax.swing.JButton();
        jButtonKhongLuu = new javax.swing.JButton();
        jTextFieldTKNoiDung = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPane.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("VẬT TƯ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã vật tư:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên vật tư:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Đơn vị tính:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giá mua:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Số lượng tồn:");

        jTextFieldMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaActionPerformed(evt);
            }
        });

        jTextFieldGiaMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGiaMuaActionPerformed(evt);
            }
        });

        jTextFieldSoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoLuongTonActionPerformed(evt);
            }
        });

        jTableVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Vật Tư", "Tên Vật Tư", "Đơn Vị Tính", "Giá Mua", "Số Lượng Tồn"
            }
        ));
        jTableVatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVatTuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVatTu);

        jButtonThem.setBackground(new java.awt.Color(229, 229, 229));
        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(255, 0, 0));
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(229, 229, 229));
        jButtonSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(255, 51, 0));
        jButtonSua.setText("Chỉnh Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonLuu.setBackground(new java.awt.Color(229, 229, 229));
        jButtonLuu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLuu.setForeground(new java.awt.Color(0, 204, 204));
        jButtonLuu.setText("Lưu");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jButtonXoa.setBackground(new java.awt.Color(229, 229, 229));
        jButtonXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(204, 51, 0));
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonDongForm.setBackground(new java.awt.Color(229, 229, 229));
        jButtonDongForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDongForm.setForeground(new java.awt.Color(204, 51, 0));
        jButtonDongForm.setText("Đóng Form");
        jButtonDongForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDongFormActionPerformed(evt);
            }
        });

        jButtonKhongLuu.setBackground(new java.awt.Color(229, 229, 229));
        jButtonKhongLuu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKhongLuu.setForeground(new java.awt.Color(0, 204, 204));
        jButtonKhongLuu.setText("Không Lưu");
        jButtonKhongLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhongLuuActionPerformed(evt);
            }
        });

        jTextFieldTKNoiDung.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextFieldTKNoiDung.setText("Nhập mã vật tư");

        jButtonTimKiem.setText("Tìm Kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneLayout = new javax.swing.GroupLayout(jPane);
        jPane.setLayout(jPaneLayout);
        jPaneLayout.setHorizontalGroup(
            jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLayout.createSequentialGroup()
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPaneLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKhongLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDongForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneLayout.createSequentialGroup()
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTKNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTimKiem))
                    .addGroup(jPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPaneLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPaneLayout.createSequentialGroup()
                                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldMa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(jPaneLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneLayout.setVerticalGroup(
            jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTKNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDongForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKhongLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        blnThem = true;
        
        jTextFieldMa.setText("");
        jTextFieldMa.setEditable(true);
        jTextFieldMa.requestFocus();
        jTextFieldTen.setText("");
        jTextFieldTen.setEditable(true);
        jTextFieldDVT.setText("");
        jTextFieldDVT.setEditable(true);
        jTextFieldGiaMua.setText("");
        jTextFieldGiaMua.setEditable(true);
        jTextFieldSoLuongTon.setText("");
        jTextFieldSoLuongTon.setEditable(true);
        
        jButtonThem.setEnabled(false);
        jButtonSua.setEnabled(false);
        jButtonXoa.setEnabled(false);
        jButtonLuu.setEnabled(true);
        jButtonKhongLuu.setEnabled(true);
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst = null;
        PreparedStatement pst1 = null;
        Connection conn = null;
        
        DefaultTableModel tblModel = (DefaultTableModel)jTableVatTu.getModel();
            
        String mavt = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 0).toString();
            
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
            String sql1 = "SELECT * FROM VATTU WHERE MAVT = ?";
            pst1 = conn.prepareStatement (sql1);
            pst1.setString(1, mavt);
            ResultSet resultSet1 = pst1.executeQuery();
            
            if(resultSet1.next() ) {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
                String sql = "DELETE FROM VATTU WHERE MAVT = ?";

                pst = conn.prepareStatement (sql);
                pst.setString(1, mavt);

                int respone = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa vật tư " + mavt +"?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(respone == JOptionPane.YES_OPTION) {
                    pst.executeUpdate();
                    ganDuLieu();
                    JOptionPane.showMessageDialog(null, "Vật tư đã được xóa thành công!");
                }
            }  else {
                ganDuLieu();
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng "+mavt+"!");
            }
                
        } catch (SQLException ex) {
            String msg = "MyModel():Lỗi kết nối cơ sở dữ liệu:\n" + ex.getMessage();
            System.out.println(msg);
        } 
        
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonDongFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDongFormActionPerformed
        // TODO add your handling code here:
        dispose();
        this.toBack();
    }//GEN-LAST:event_jButtonDongFormActionPerformed

    private void jButtonKhongLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhongLuuActionPerformed
        // TODO add your handling code here:
        ganDuLieu();
        
        jButtonThem.setEnabled(true);
        jButtonSua.setEnabled(true);
    }//GEN-LAST:event_jButtonKhongLuuActionPerformed

    private void jTextFieldGiaMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGiaMuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGiaMuaActionPerformed

    private void jTextFieldSoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoLuongTonActionPerformed

    private void jTextFieldMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaActionPerformed

    private void jTableVatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVatTuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTableVatTu.getModel();
        
        String mavt = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 0).toString();
        String tenvt = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 1).toString();
        String dvt = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 2).toString();
        String giamua = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 3).toString();
        String slton = tblModel.getValueAt(jTableVatTu.getSelectedRow(), 4).toString();
        
        jTextFieldMa.setText(mavt);
        jTextFieldMa.setEditable(false);
        jTextFieldTen.setText(tenvt);
        jTextFieldTen.setEditable(false);
        jTextFieldDVT.setText(dvt);
        jTextFieldDVT.setEditable(false);
        jTextFieldGiaMua.setText(giamua);
        jTextFieldGiaMua.setEditable(false);
        jTextFieldSoLuongTon.setText(slton);
        jTextFieldSoLuongTon.setEditable(false);

        jButtonThem.setEnabled(true);
        jButtonSua.setEnabled(true);
        jButtonXoa.setEnabled(true);
        
    }//GEN-LAST:event_jTableVatTuMouseClicked

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        blnThem = false;
        blnSua = true;
        jTextFieldMa.setEditable(false);
        jTextFieldTen.setEditable(true);
        jTextFieldTen.requestFocus();
        jTextFieldDVT.setEditable(true);
        jTextFieldGiaMua.setEditable(true);
        jTextFieldSoLuongTon.setEditable(true);
        
        jButtonThem.setEnabled(false);
        jButtonSua.setEnabled(false);
        jButtonXoa.setEnabled(false);
        jButtonLuu.setEnabled(true);
        jButtonKhongLuu.setEnabled(true);
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        // TODO add your handling code here:
        String mavt = jTextFieldMa.getText();
        String tenvt = jTextFieldTen.getText();
        String dvt = jTextFieldDVT.getText();
        String giamua = jTextFieldGiaMua.getText();
        String slton = jTextFieldSoLuongTon.getText();
        
        if (mavt.equals("") || tenvt.equals("") || dvt.equals("") || giamua.equals("") || slton.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Trường không được bỏ trống", "Lỗi", 1);
        } else {
            
            PreparedStatement pst = null;
            Connection conn = null;
            if(blnThem) {
                try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
                    String sql = "INSERT VATTU VALUES(?,?,?,?,?)";

                    pst = conn.prepareStatement (sql);
                    pst.setString(1, mavt);
                    pst.setString(2, tenvt);
                    pst.setString(3, dvt);
                    pst.setString(4, giamua);
                    pst.setString(5, slton);

                    int resultSet = pst.executeUpdate();

                    if(resultSet>=1) {
                        ganDuLieu();
                        JOptionPane.showMessageDialog(null, "Vật tư được thêm thành công!");
                    } else { 
                        JOptionPane.showMessageDialog(null, "Không thể thêm vật tư mới!");
                    }
                
                } catch (SQLException ex) {
                    String msg = ex.getMessage();
                    JOptionPane.showMessageDialog(null, msg);
                } 
            } else if(blnSua) {
                
                try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
                    String sql = "UPDATE VATTU SET TENVT=?, DVT=?, GIAMUA=?, SLTON=? where MAVT='"+mavt+"'";
                    
                    pst = conn.prepareStatement (sql);
                    pst.setString(1, tenvt);
                    pst.setString(2, dvt);
                    pst.setString(3, giamua);
                    pst.setString(4, slton);

                    int resultSet = pst.executeUpdate();
                    
                    if(resultSet>=1) {
                        JOptionPane.showMessageDialog(null, "Vật tư được cật nhật thành công!");
                        ganDuLieu();
                    } else {
                        JOptionPane.showMessageDialog(null, "Không thể cập nhật vật tư mới!");
                    }
                } catch (SQLException ex) {
                        String msg = ex.getMessage();
                        JOptionPane.showMessageDialog(null, msg);
                } 

            }
            
        }
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        String mavt = jTextFieldTKNoiDung.getText();
        PreparedStatement pst = null;
        Connection conn = null;
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/qlvattu","root","Thang123!");
            String sql = "SELECT * FROM VATTU WHERE MAVT LIKE '%"+mavt+"%'";
            pst = conn.prepareStatement(sql);
            ResultSet resultSet = pst.executeQuery();
            jTableVatTu.setModel(DbUtils.resultSetToTableModel(resultSet));
            
            if(jTableVatTu.getRowCount() > 0) {
                jTextFieldMa.setText("");
                jTextFieldTen.setText("");
                jTextFieldDVT.setText("");
                jTextFieldGiaMua.setText("");
                jTextFieldSoLuongTon.setText("");
            } else {
                if(!resultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Mã vật tư không tìm thấy");
                    jTextFieldTKNoiDung.setText("");
                    ganDuLieu();
                }
                
            }
            
                
        } catch (SQLException ex) {
            String msg = "MyModel(): Error Connecting to Database:\n" + ex.getMessage();
            System.out.println(msg);
        } 
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VatTuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VatTuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VatTuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VatTuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VatTuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDongForm;
    private javax.swing.JButton jButtonKhongLuu;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPane;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableVatTu;
    private javax.swing.JTextField jTextFieldDVT;
    private javax.swing.JTextField jTextFieldGiaMua;
    private javax.swing.JTextField jTextFieldMa;
    private javax.swing.JTextField jTextFieldSoLuongTon;
    private javax.swing.JTextField jTextFieldTKNoiDung;
    private javax.swing.JTextField jTextFieldTen;
    // End of variables declaration//GEN-END:variables
}
